name: CI ASP.NET

on:
  push:
    branches:
      - main  # Executa quando houver push na branch 'main'
  pull_request:
    types: [opened, synchronize, reopened]  # Executa em PRs abertos, sincronizados ou reabertos

jobs:
  ci-aspnet:
    uses: jpvieirah/central-reusable/.github/workflows/aspnet-build-reusable.yml@main  # Referencia o arquivo reutilizável
    with:
      language: "aspnet"
      environment: "ci"
      dotnet-version: "7.0"  # Passando a versão do .NET
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Passando o SONAR_TOKEN como secret
