name: CI ASP.NET

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - "aspnet-pipelines/**"
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - "aspnet-pipelines/**"

jobs:
  ci-aspnet:
    uses: jpvieirah/central-reusable/.github/workflows/aspnet-build-reusable.yml@develop
    with:
      language: "aspnet"
      environment: "ci"
      dotnet-version: "7.0"
    secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
