name: CI ASP.NET

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - "aspnet-pipelines/**"  # Dispara o workflow apenas se houver alterações na pasta "aspnet-pipelines"
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - "aspnet-pipelines/**"  # Dispara o workflow apenas se houver alterações na pasta "aspnet-pipelines"
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  ci-aspnet:
    uses: jpvieirah/central-reusable/.github/workflows/aspnet-build-reusable.yml@main  # Referencia o arquivo reutilizável
    with:
      language: "aspnet"
      environment: "ci"
      dotnet-version: "7.0"  # Passando a versão do .NET
      project-path: "aspnet-pipelines/aspnet-pipelines.csproj"  # Caminho para o seu projeto ASP.NET
